import { Ms as PluginRuntime, Oa as OpenClawPluginApi, vd as emptyPluginConfigSchema } from "../agent-harness-runtime-D1Ww9PgY.js";
import { g as ChannelMessageActionContext } from "../types.core-D41vZ0PO.js";
import { n as normalizeAccountId, t as DEFAULT_ACCOUNT_ID } from "../account-id-Dh6XMgGH.js";
import { t as ChannelPlugin } from "../types.plugin-BovxZMna.js";
import { i as buildChannelConfigSchema } from "../config-schema-C27HzEVf.js";
import { o as migrateBaseNameToDefaultAccount, t as applyAccountNameToChannelSection } from "../setup-helpers-DVxqIPuo.js";
import { i as setAccountEnabledInConfigSection, r as deleteAccountFromConfigSection, t as clearAccountEntryFields } from "../config-helpers-A0Pcht-G.js";
import { n as formatPairingApproveHint } from "../helpers-Zx-X_EgU.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../pairing-message-CFs8lRw3.js";
import { t as getChatChannelMeta } from "../channel-plugin-common-DBSJYMEr.js";
export { type ChannelMessageActionContext, type ChannelPlugin, DEFAULT_ACCOUNT_ID, type OpenClawPluginApi, PAIRING_APPROVED_MESSAGE, type PluginRuntime, applyAccountNameToChannelSection, buildChannelConfigSchema, clearAccountEntryFields, deleteAccountFromConfigSection, emptyPluginConfigSchema, formatPairingApproveHint, getChatChannelMeta, migrateBaseNameToDefaultAccount, normalizeAccountId, setAccountEnabledInConfigSection };