import { Bi as buildThreadAwareOutboundSessionRoute, Cs as PluginCommandContext, Hi as createChatChannelPlugin, Ii as ChannelOutboundSessionRouteParams, Ji as stripChannelTargetPrefix, Ms as PluginRuntime, Oa as OpenClawPluginApi, Ui as defineChannelPluginEntry, Vi as createChannelPluginBase, Wi as defineSetupPluginEntry, Yi as stripTargetKindPrefix, qi as recoverCurrentThreadSessionId, zi as buildChannelOutboundSessionRoute } from "../agent-harness-runtime-D1Ww9PgY.js";
import { r as OpenClawConfig } from "../types.openclaw-DRlyXvhd.js";
import { xt as ChannelConfigUiHint } from "../types.channels-BVWycIjM.js";
import { t as ChannelPlugin } from "../types.plugin-BovxZMna.js";
import { i as buildChannelConfigSchema } from "../config-schema-C27HzEVf.js";
import { t as clearAccountEntryFields } from "../config-helpers-A0Pcht-G.js";
import { r as parseOptionalDelimitedEntries } from "../helpers-Zx-X_EgU.js";
import { u as tryReadSecretFileSync } from "../secret-file-DwypAJjM.js";
import { t as createChannelConfigUiHints } from "../channel-core-CEU_-Osx.js";
export { type ChannelConfigUiHint, type ChannelOutboundSessionRouteParams, type ChannelPlugin, type OpenClawConfig, type OpenClawPluginApi, type PluginCommandContext, type PluginRuntime, buildChannelConfigSchema, buildChannelOutboundSessionRoute, buildThreadAwareOutboundSessionRoute, clearAccountEntryFields, createChannelConfigUiHints, createChannelPluginBase, createChatChannelPlugin, defineChannelPluginEntry, defineSetupPluginEntry, parseOptionalDelimitedEntries, recoverCurrentThreadSessionId, stripChannelTargetPrefix, stripTargetKindPrefix, tryReadSecretFileSync };